services:

    zabbix-postgre:
      image: postgres:16
      container_name: zabbix-postgre
      hostname: zabbix-postgre
      restart: unless-stopped
      environment:
        TZ: Europe/Moscow
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - 5432:5432
      networks:
        zabbix_net:
          ipv4_address: 172.16.0.5
      volumes:
        - ./postgredb-data:/var/lib/postgresql/data/
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbixdb -h zabbix-postgre"]
        interval: 10s
        timeout: 3s
        retries: 3

    zabbix-server:
      build:
        context: .
        dockerfile: Dockerfile-zabbix-server
      image: zabbix/zabbix-server-pgsql:test1
      container_name: zabbix-server
      hostname: zabbix-server
      restart: unless-stopped
      environment:
        DB_SERVER_HOST: zabbix-postgre
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ZBX_HOUSEKEEPINGFREQUENCY: 1
        ZBX_MAXHOUSEKEEPERDELETE: 500
        ZBX_PROBLEMHOUSEKEEPINGFREQUENCY: 60
        ZBX_CACHESIZE: 256M
        ZBX_ENABLE_SNMP_TRAPS: true
        ZBX_STARTTRAPPERS: 5
        ZBX_STARTIPMIPOLLERS: 5
        ZBX_IPMIPOLLERS: 3
        ZBX_STARTPOLLERS: 100
        ZBX_STARTPOLLERSUNREACHABLE: 2
      ports:
         - 10051:10051
      networks:
         zabbix_net:
           ipv4_address: 172.16.0.4
      depends_on:
         zabbix-postgre:
            condition: service_healthy

    zabbix-web:
      build:
        context: .
        dockerfile: Dockerfile-zabbix-webserver
      image: zabbix-web:test1
      container_name: zabbix-web
      hostname: zabbix-web
      restart: unless-stopped
      environment:
        DB_SERVER_HOST: zabbix-postgre
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        ZBX_SERVER_HOST: zabbix-server
        ZBX_SERVER_NAME: ${ZBX_SERVER_NAME}
      volumes:
         - ./zabbix-ssl/zabbix.crt:/etc/ssl/nginx/zabbix.crt:ro
         - ./zabbix-ssl/zabbix.key:/etc/ssl/nginx/zabbix.key:ro
         - ./zabbix-ssl/dhparam.pem:/etc/ssl/nginx/dhparam.pem:ro
      ports:
         - 443:8443
      networks:
         zabbix_net:
           ipv4_address: 172.16.0.3
      depends_on:
          zabbix-postgre:
             condition: service_healthy


#    zabbix-agent-2:
#      build:
#        context: .
#        dockerfile: Dockerfile-zabbix-agent2
#      image: zabbix-agent2:test1
#      container_name: zabbix-agent2
#      restart: unless-stopped
#      environment:
#        ZBX_HOSTNAME: zabbix-agent2
#        ZBX_METADATAITEM: systemc.uname
#        ZBX_DENYKEY: system.run[*]
#        ZBX_ACTIVE_ALLOW: true
#        ZBX_PASSIVE_ALLOW: true
#        ZBX_UNSAFEUSERPARAMETERS: 1
#        ZBX_USERPARAMETER: 'domain.expiry[*],/etc/zabbix/scripts/check_domain_expiry.sh $1'
#      volumes:
#          - ./scripts:/etc/zabbix/scripts:ro
#      networks:
#          - zabbix_net


volumes:
    postgredb-data:
    zabbix-ssl:

networks:
    zabbix_net:
      driver: bridge
      ipam:
         config:
           - subnet: 172.16.0.0/16
             gateway: 172.16.0.1
